### ISSUE TITLE
[COMPILER] https://minbox.com/gi/h6V9KQO/download [ERROR 404]

### ISSUE THREAD

**Issue by xZero707** [jaredallard/phc-win#11]
```
--2016-07-17 02:08:15--  https://minbox.com/gi/h6V9KQO/download
Resolving minbox.com... 52.8.108.238, 54.183.251.72
Connecting to minbox.com|52.8.108.238|:443... connected.
WARNING: cannot verify minbox.com's certificate, issued by `/C=US/O=GeoTrust Inc./CN=RapidSSL SHA256 CA - G4':
  Unable to locally verify the issuer's authority.
WARNING: certificate common name `*.minbox.com' doesn't match requested host name `minbox.com'.
HTTP request sent, awaiting response... 404 Not Found
2016-07-17 02:08:17 ERROR 404: Not Found.
```

**Comment by jaredallard** [comment]
Hmmm... for whatever the reason, the host appears to have removed the file.

**Comment by jaredallard** [comment]
Should be able to replace it with this link if I didn't add anything to the zip. http://windows.php.net/downloads/php-sdk/php-sdk-binary-tools-20110915.zip

**Comment by xZero707** [comment]
I see. Seems like they changed things a lot, not only removed the file? Anyway, I guess this one you sent me will work. Thanks.

**Comment by xZero707** [comment]
Hi! Me again. I didn't wanted to open a new issue, but I undoubtedly have it - with building:
Please note: For compatibility sake I installed VS 2012. 

After running make and everything else passed I get: 

```
Compiling embeder2... 
'vcvarsall.bat' is not recognized as an internal or external command,
operable program or batch file.
```

So I gone to src\depends\embeder2
And tried to edit file make_embeder.cmd:
-- call vcvarsall.bat
++ call "%VCPATH%\vcvarsall.bat"

Tried again... 
```
make
...
...
...
Compiling embeder2...

X:\dev\PHC-WIN\BUILD>
```

I cannot seem to find error but I have tried to build embeder2 manually:
```
X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src>call "D:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\vcvarsall.bat"

X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src>msbuild
Microsoft (R) Build Engine version 4.6.1038.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 18/07/2016 03:52:02.
Project "X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src\embeder.
sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug console|Win32".
Project "X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src\embeder.
sln" (1) is building "X:\dev\PHC-WIN\BUILD\src\depends\embeder2
\src\embeder.vcxproj" (2) on node 1 (default targets).
Project file contains ToolsVersion="12.0". This toolset may be unknown or missi
ng, in which case you may be able to resolve this by installing the appropriate
 version of MSBuild, or the build may have been forced to a particular ToolsVer
sion for policy reasons. Treating the project as if it had ToolsVersion="4.0".
For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.t
argets(44,5): error MSB8020: The builds tools for v120 (Platform Toolset = 'v12
0') cannot be found. To build using the v120 build tools, either click the Proj
ect menu or right-click the solution, and then select "Update VC++ Projects..."
. Install v120 to build using the v120 build tools. [X:\dev\PHC
-WIN\BUILD\src\depends\embeder2\src\embeder.vcxproj]
Done Building Project "X:\dev\PHC-WIN\BUILD\src\depends\embeder
2\src\embeder.vcxproj" (default targets) -- FAILED.

Done Building Project "X:\dev\PHC-WIN\BUILD\src\depends\embeder
2\src\embeder.sln" (default targets) -- FAILED.


Build FAILED.

"X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src\embeder.sln" (de
fault target) (1) ->
"X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src\embeder.vcxproj"
 (default target) (2) ->
(PlatformPrepareForBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform
.targets(44,5): error MSB8020: The builds tools for v120 (Platform Toolset = 'v
120') cannot be found. To build using the v120 build tools, either click the Pr
oject menu or right-click the solution, and then select "Update VC++ Projects..
.". Install v120 to build using the v120 build tools. [X:\dev\P
HC-WIN\BUILD\src\depends\embeder2\src\embeder.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.77
```

**Comment by jaredallard** [comment]
I can't do much about this until Wednesday but Ill look into it then

On Sun, Jul 17, 2016, 7:06 PM Aleksandar Puharic <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi! Me again. I didn't wanted to open a new issue, but I undoubtedly have it - with building:
Please note: For compatibility sake I installed VS 2012.

After running make and everything else passed I get:

Compiling embeder2...
'vcvarsall.bat' is not recognized as an internal or external command,
operable program or batch file.


So I gone to src\depends\embeder2
And tried to edit file make_embeder.cmd:
-- call vcvarsall.bat
++ call "%VCPATH%\vcvarsall.bat"

Tried again...

make
...
...
...
Compiling embeder2...

X:\dev\PHC-WIN\BUILD>


I cannot seem to find error but I have tried to build embeder2 manually:

X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src>call "D:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\vcvarsall.bat"

X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src>msbuild
Microsoft (R) Build Engine version 4.6.1038.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 18/07/2016 03:52:02.
Project "X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src\embeder.
sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug console|Win32".
Project "X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src\embeder.
sln" (1) is building "X:\dev\PHC-WIN\BUILD\src\depends\embeder2
\src\embeder.vcxproj" (2) on node 1 (default targets).
Project file contains ToolsVersion="12.0". This toolset may be unknown or missi
ng, in which case you may be able to resolve this by installing the appropriate
 version of MSBuild, or the build may have been forced to a particular ToolsVer
sion for policy reasons. Treating the project as if it had ToolsVersion="4.0".
For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.t
argets(44,5): error MSB8020: The builds tools for v120 (Platform Toolset = 'v12
0') cannot be found. To build using the v120 build tools, either click the Proj
ect menu or right-click the solution, and then select "Update VC++ Projects..."
. Install v120 to build using the v120 build tools. [X:\dev\PHC
-WIN\BUILD\src\depends\embeder2\src\embeder.vcxproj]
Done Building Project "X:\dev\PHC-WIN\BUILD\src\depends\embeder
2\src\embeder.vcxproj" (default targets) -- FAILED.

Done Building Project "X:\dev\PHC-WIN\BUILD\src\depends\embeder
2\src\embeder.sln" (default targets) -- FAILED.


Build FAILED.

"X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src\embeder.sln" (de
fault target) (1) ->
"X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src\embeder.vcxproj"
 (default target) (2) ->
(PlatformPrepareForBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform
.targets(44,5): error MSB8020: The builds tools for v120 (Platform Toolset = 'v
120') cannot be found. To build using the v120 build tools, either click the Pr
oject menu or right-click the solution, and then select "Update VC++ Projects..
.". Install v120 to build using the v120 build tools. [X:\dev\P
HC-WIN\BUILD\src\depends\embeder2\src\embeder.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.77

**Comment by xZero707** [comment]
Okay Jared. Thanks. 

All the best
