### ISSUE TITLE
Compilation problem: Crashes at "Compiling embeder2 "

### ISSUE THREAD

**Issue by xZero707** [jaredallard/phc-win#12]
Hi! Me again. I didn't wanted to open a new issue, but I undoubtedly have it - with building:
Please note: For compatibility sake I installed VS 2012. 

After running make and everything else passed I get: 

```
Compiling embeder2... 
'vcvarsall.bat' is not recognized as an internal or external command,
operable program or batch file.
```

So I gone to src\depends\embeder2
And tried to edit file make_embeder.cmd:
**call vcvarsall.bat** > CHANGED TO > **call "%VCPATH%\vcvarsall.bat"**

Tried again... 

```
make
...
...
...
Compiling embeder2...

X:\dev\PHC-WIN\BUILD>
```

After about half minute of "Compiling embeder2..." it just exits without any usable error info.

I cannot seem to find error but I have tried to build embeder2 manually:

```
X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src>call "D:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\vcvarsall.bat"

X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src>msbuild
Microsoft (R) Build Engine version 4.6.1038.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 18/07/2016 03:52:02.
Project "X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src\embeder.
sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug console|Win32".
Project "X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src\embeder.
sln" (1) is building "X:\dev\PHC-WIN\BUILD\src\depends\embeder2
\src\embeder.vcxproj" (2) on node 1 (default targets).
Project file contains ToolsVersion="12.0". This toolset may be unknown or missi
ng, in which case you may be able to resolve this by installing the appropriate
 version of MSBuild, or the build may have been forced to a particular ToolsVer
sion for policy reasons. Treating the project as if it had ToolsVersion="4.0".
For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.t
argets(44,5): error MSB8020: The builds tools for v120 (Platform Toolset = 'v12
0') cannot be found. To build using the v120 build tools, either click the Proj
ect menu or right-click the solution, and then select "Update VC++ Projects..."
. Install v120 to build using the v120 build tools. [X:\dev\PHC
-WIN\BUILD\src\depends\embeder2\src\embeder.vcxproj]
Done Building Project "X:\dev\PHC-WIN\BUILD\src\depends\embeder
2\src\embeder.vcxproj" (default targets) -- FAILED.

Done Building Project "X:\dev\PHC-WIN\BUILD\src\depends\embeder
2\src\embeder.sln" (default targets) -- FAILED.


Build FAILED.

"X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src\embeder.sln" (de
fault target) (1) ->
"X:\dev\PHC-WIN\BUILD\src\depends\embeder2\src\embeder.vcxproj"
 (default target) (2) ->
(PlatformPrepareForBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform
.targets(44,5): error MSB8020: The builds tools for v120 (Platform Toolset = 'v
120') cannot be found. To build using the v120 build tools, either click the Pr
oject menu or right-click the solution, and then select "Update VC++ Projects..
.". Install v120 to build using the v120 build tools. [X:\dev\P
HC-WIN\BUILD\src\depends\embeder2\src\embeder.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.77
```

Googling for **error MSB8020: The builds tools for v120 (Platform Toolset = 'v 120') cannot be found.** : http://stackoverflow.com/questions/19801072/the-builds-tools-for-v120-platform-toolset-v120-cannot-be-found

**Comment by jaredallard** [comment]
Is the vcvars for vs2012?

**Comment by xZero707** [comment]
Yes. I actually had VS2015 at first but it didn't worked as vcvarsall.bat was missing. So I think we can say that it doesn't work at all for VS2015.

I installed vs2012 and vcvarsall.bat is default:

```
@echo off
if "%1" == "" goto x86
if not "%2" == "" goto usage

if /i %1 == x86       goto x86
if /i %1 == amd64     goto amd64
if /i %1 == x64       goto amd64
if /i %1 == arm       goto arm
if /i %1 == x86_arm   goto x86_arm
if /i %1 == x86_amd64 goto x86_amd64
goto usage

:x86
if not exist "%~dp0bin\vcvars32.bat" goto missing
call "%~dp0bin\vcvars32.bat"
goto :SetVisualStudioVersion

:amd64
if not exist "%~dp0bin\amd64\vcvars64.bat" goto missing
call "%~dp0bin\amd64\vcvars64.bat"
goto :SetVisualStudioVersion

:arm
if not exist "%~dp0bin\arm\vcvarsarm.bat" goto missing
call "%~dp0bin\arm\vcvarsarm.bat"
goto :SetVisualStudioVersion

:x86_amd64
if not exist "%~dp0bin\x86_amd64\vcvarsx86_amd64.bat" goto missing
call "%~dp0bin\x86_amd64\vcvarsx86_amd64.bat"
goto :SetVisualStudioVersion

:x86_arm
if not exist "%~dp0bin\x86_arm\vcvarsx86_arm.bat" goto missing
call "%~dp0bin\x86_arm\vcvarsx86_arm.bat"
goto :SetVisualStudioVersion

:SetVisualStudioVersion
set VisualStudioVersion=11.0
goto :eof

:usage
echo Error in script usage. The correct usage is:
echo     %0 [option]
echo where [option] is: x86 ^| amd64 ^| arm ^| x86_amd64 ^| x86_arm
echo:
echo For example:
echo     %0 x86_amd64
goto :eof

:missing
echo The specified configuration type is missing.  The tools for the
echo configuration might not be installed.
goto :eof

```

**Comment by jaredallard** [comment]
Ok! I'll look into this on my machine tonight!

On Thu, Jul 21, 2016 at 4:53 PM Aleksandar Puharic <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes. I actually had VS2015 at first but it didn't worked as vcvarsall.bat was missing. So I think we can say that it doesn't work at all for VS2015.

I installed vs2012 and vcvarsall.bat is default:

@echo off
if "%1" == "" goto x86
if not "%2" == "" goto usage

if /i %1 == x86       goto x86
if /i %1 == amd64     goto amd64
if /i %1 == x64       goto amd64
if /i %1 == arm       goto arm
if /i %1 == x86_arm   goto x86_arm
if /i %1 == x86_amd64 goto x86_amd64
goto usage

:x86
if not exist "%~dp0bin\vcvars32.bat" goto missing
call "%~dp0bin\vcvars32.bat"
goto :SetVisualStudioVersion

:amd64
if not exist "%~dp0bin\amd64\vcvars64.bat" goto missing
call "%~dp0bin\amd64\vcvars64.bat"
goto :SetVisualStudioVersion

:arm
if not exist "%~dp0bin\arm\vcvarsarm.bat" goto missing
call "%~dp0bin\arm\vcvarsarm.bat"
goto :SetVisualStudioVersion

:x86_amd64
if not exist "%~dp0bin\x86_amd64\vcvarsx86_amd64.bat" goto missing
call "%~dp0bin\x86_amd64\vcvarsx86_amd64.bat"
goto :SetVisualStudioVersion

:x86_arm
if not exist "%~dp0bin\x86_arm\vcvarsx86_arm.bat" goto missing
call "%~dp0bin\x86_arm\vcvarsx86_arm.bat"
goto :SetVisualStudioVersion

:SetVisualStudioVersion
set VisualStudioVersion=11.0
goto :eof

:usage
echo Error in script usage. The correct usage is:
echo     %0 [option]
echo where [option] is: x86 ^| amd64 ^| arm ^| x86_amd64 ^| x86_arm
echo:
echo For example:
echo     %0 x86_amd64
goto :eof

:missing
echo The specified configuration type is missing.  The tools for the
echo configuration might not be installed.
goto :eof

**Comment by jaredallard** [comment]
Just got a VM setup and a week of work, so now I can try it. I'll be setting up a slack for the project soon

On Thu, Aug 4, 2016, 06:42 Aleksandar Puharic <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi! Anything new?
I'm going to test it out with VS2013.

**Comment by jaredallard** [comment]
@xZero707 Can't confirm but this is likely because of not using VS2013. PHP 5.6 can't compile with it. Embeder2 just isn't targetting v140, which is what that means. Simple fix

**Comment by jaredallard** [comment]
So, since PHP 7 targets v140. I've ported embeder & win32std to PHP 7. WinBinder isn't technically required for this project, so this will enable PHP7 support soon!
