### ISSUE TITLE
Could not compile from source

### ISSUE THREAD

**Issue by gianx89** [jaredallard/phc-win#15]
Hi,
I'm trying to compile phc-win from the main branch (the one which supports vs2015 and php7). When I launch gulp build-all I get the following error:

Using gulpfile \phc-win\gulpfile.js
Task 'build-all' is not in your gulp-file
Please check the documentation for proper gulpfile formatting

How can I solve it?

**Comment by jaredallard** [comment]
Hey! master branch isn't in any way buildable right now, if you use the old branch you should be able to modify the config to compile php7 and support php7, but would have to have the winbinder extensions and etc use the php7 branches.
