### ISSUE TITLE
Ability to compile phar archives into exe

### ISSUE THREAD

**Issue by joncutrer** [jaredallard/phc-win#8]
I would be nice to package up and compile a phar application using the tool.

**Comment by jaredallard** [comment]
Hello! Thanks for the suggestion. I'm much a of a PHP programmer anymore, and I never really got into phar. What exactly is it, and what does it comprise of? If it's not a huge ordeal, I'd totally be willing to do that in my freetime (which is also very limited sadly).

**Comment by joncutrer** [comment]
Phar is an archived self contained php application that can be executed
i.e. php app.phar. Support can be achieved if the bundled php runtime has
the phar extension enabled and certain phar related php.ini settings are
present.

This should overcome limitations of unsupported require() statements and
add support for psr-0 and namespaces ( I think).

**Comment by jaredallard** [comment]
Alright, thanks. Will look into it!

**Comment by xZero707** [comment]
I would also like to see this. I would help with development if you can provide me more documentation.
