### ISSUE TITLE
JSON encode/decode support

### ISSUE THREAD

**Issue by xZero707** [jaredallard/phc-win#9]
There is no JSON in PHP build you supplied. 

PHP Fatal error:  Call to undefined function json_decode()
PHP Fatal error:  Call to undefined function json_encode()

**Comment by jaredallard** [comment]
Quick fix is to have it build your own, requires VC2012(+?) and addition of the command line in fetch_src.cmd:

```diff
--- a/fetch_src.cmd
+++ b/fetch_src.cmd
  :: PHP options
  @SET PHP_VER=5.6.6
- @SET PHP_ARGS=--disable-all --enable-embed --enable-cli --with-winbinder --with-win32std
+ @SET PHP_ARGS=--disable-all --enable-embed --enable-cli --with-winbinder --with-win32std --enable-json
  @SET PHP_SDK=https://minbox.com/gi/h6V9KQO/download'

  :: Check minimal requirements are here.
  @echo Checking for prerequisites.
```

**Comment by xZero707** [comment]
Nice. I have VC2015, is it compatible?
Also, how to include other custom extensions, eg. CURL? PECL? Is it even possible?

Your work is great and appreciated. Keep it up!

**Comment by jaredallard** [comment]
You can add other extensions via the same way pretty much, just read up the fetch_src script it literally walks through the entire installation and does it all for you! I actually build this project any time I need a PHP custom modification because it's so reproducible.

**Comment by xZero707** [comment]
Okay then. Thank you for your time and support!
